# Generated by Django 4.2 on 2023-05-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actAsAdUnit', models.BooleanField(blank=True, default=False, null=True, verbose_name='actAsAdUnit')),
                ('inSlide', models.BooleanField(blank=True, default=None, null=True, verbose_name='inSlide')),
                ('position', models.CharField(blank=True, default='bottom-left', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='generalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoPlay', models.BooleanField(blank=True, default=False, null=True, verbose_name='autoPlay')),
                ('pauseAdWhenOutOfView', models.BooleanField(blank=True, default=False, null=True, verbose_name='pauseAdWhenOutOfView')),
                ('continuePlaylist', models.BooleanField(blank=True, default=False, null=True, verbose_name='continuePlaylist')),
                ('loop', models.BooleanField(blank=True, default=False, null=True, verbose_name='loop')),
                ('muted', models.BooleanField(blank=True, default=False, null=True, verbose_name='muted')),
                ('pauseWhenOutOfView', models.BooleanField(blank=True, default=False, null=True, verbose_name='pauseWhenOutOfView')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stick', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sticky')),
            ],
        ),
        migrations.CreateModel(
            name='StickyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='player/video/logo/')),
                ('src', models.URLField(blank=True, default='127.0.0.1:8000/static/player/video/play.min.js', null=True)),
                ('logoPos', models.IntegerField(blank=True, null=True)),
                ('logoUrl', models.URLField(blank=True, null=True)),
                ('start_muted', models.BooleanField(default=False)),
                ('start_volume', models.IntegerField(blank=True, null=True)),
                ('monetize', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('ad_preload', models.BooleanField(default=False)),
                ('ad_postload', models.BooleanField(default=False)),
                ('autoplay', models.BooleanField(default=True)),
                ('volume', models.BooleanField(default=True)),
                ('fullscreen', models.BooleanField(default=True)),
                ('controls', models.BooleanField(default=True)),
                ('controlsBehavior', models.CharField(blank=True, default='visible', max_length=200, null=True)),
                ('afterPlaylistEnd', models.CharField(blank=True, default='stop', max_length=200, null=True)),
                ('playlistPlayback', models.CharField(blank=True, default='continuous', max_length=200, null=True)),
                ('shuffle', models.BooleanField(default=True)),
                ('autohide_ad_controls', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoplaylist')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.adunit')),
                ('generalSettings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.generalsettings')),
                ('sticky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.sticky')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sticky',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.stickyposition'),
        ),
        migrations.CreateModel(
            name='PlayerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.playerposition')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.mobileposition')),
            ],
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='mobileSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.mobilesize'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='playerSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.playersize'),
        ),
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoplayer')),
                ('playlist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoplaylist')),
            ],
        ),
    ]
