# Generated by Django 4.2 on 2023-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplayer',
            name='src',
            field=models.URLField(blank=True, default='64.227.170.236/static/player/video/play.min.js', null=True),
        ),
    ]
