# Generated by Django 4.2 on 2023-04-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_contentunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoplaylist',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoplaylist'),
        ),
    ]
